### PR TITLE
Allow the unsetting of default request options

### PR DESCRIPTION
**Pull request by adrian-chang**
Sometimes we want to remove certain keys from a merged object, this will allow that.

### CODE REVIEW

**Comment by indexzero** [comment]
+1 but I don't have merge rights.

**Comment by lpinca** [comment]
Shouldn't

``` js
merge({ foo: 'bar' }, { foo: undefined });
```

return

``` js
{ foo: undefined }
```

?

**Comment by 3rd-Eden** [comment]
@lpinca I agree with that.

**Comment by 3rd-Eden** [comment]
@amchang Do you have a use-case where deleting of properties is required?

**Comment by adrian-chang** [comment]
If you use a FormData, you want the browser to manually set the Content-Type / Disposition headers automatically. 

As in the where the code is appending the headers, you wouldn't want to append any 'Content-Type' as it does in the defaults.

I'm actually going to close this right now as I just reviewed that 'undefined' values for headers are ignored, I missed that earlier.

**Pull request closed without merging**
